apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app
  labels:
    app: your-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      initContainers:
      - name: check-rabbitmq
        image: busybox
        command: ['sh', '-c', 'until nslookup vprodb; do echo waiting for rabbitmq; sleep 2; done;']
      - name: check-memcached
        image: busybox
        command: ['sh', '-c', 'until nslookup memcached; do echo waiting for memcached; sleep 2; done;']
      - name: check-vprodb
        image: busybox
        command: ['sh', '-c', 'until nslookup rabbitmq; do echo waiting for vprodb; sleep 2; done;']
      containers:
      - name: your-app
        image: your-app-image:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: your-app-service
spec:
  selector:
    app: your-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
